In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('./dataset/train.csv')
df.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [3]:
df.shape

(77299, 11)

In [4]:
test = pd.read_csv('./dataset/test.csv')
test.head()

,Index,geohash,day,timestamp,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,49,2:15,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02z9,49,2:15,Residential,1,Not Allowed,No,6.476213,Snowy
2,2,qp02yf,49,2:15,Residential,3,Allowed,Yes,22.318203,Sunny
3,3,qp02z6,49,2:15,Residential,2,Not Allowed,Yes,NaN,Rainy
4,4,qp02zd,49,2:15,Residential,1,Not Allowed,No,18.266162,Foggy

In [5]:
test.shape

(41778, 10)

In [6]:
categorical_cols = df.select_dtypes(include=['object']).columns
print(categorical_cols.tolist())

['geohash', 'timestamp', 'RoadType', 'LargeVehicles', 'Landmarks', 'Weather']

In [7]:
df['day'].unique()

array([48, 49])

In [9]:
df['geohash'].value_counts()

geohash
qp03wd    105
qp03wf    105
qp09t0    105
qp03w9    105
qp03x3    105
         ...
qp08gs      1
qp08fq      1
qp0d1t      1
qp09vc      1
qp09jc      1
Name: count, Length: 1249, dtype: int64